### ISSUE TITLE
Standardize return types across all endpoint operations

### ISSUE THREAD

**Issue by Ramen-Noodle** [irods/irods_client_http_python#21]

**Comment by trel** [comment]
this commit seems... weird?   lots of duplicate/redundant `rdict = r.json()` calls?

**Comment by trel** [comment]
The next commit (https://github.com/irods/irods_client_http_python/commit/4c23f1d0846a9044d493bac5e4afe9bc1bc9d5e4) removed the duplicate lines.

So ignore my previous question.

**Comment by korydraughn** [comment]
@Ramen-Noodle Now that we have #32, is there any reason to keep this issue open?

**Comment by Ramen-Noodle** [comment]
> @Ramen-Noodle Now that we have #32, is there any reason to keep this issue open?

I reopened it since I changed the format of the return data, it will be closed after the PR is merged
